### ISSUE TITLE
iptables rules do not seem to handle endoints changing security group

### ISSUE THREAD

**Issue by Lukasa** [Metaswitch/calico#55]
Each packet received or sent on a machine should only pass through the iptables rules that apply for the VM it's being sent to or received from. However, Felix currently doesn't do that filtering correctly: instead, it applies all iptables rules for all VMs on the box.

In practice, this means that only one security group applies to all VMs on the box, as the default behaviour for a security group is unconditional.

This is a critical security bug that needs to be resolved.

Below is the output from a test machine. This machine contains three VMs. Note that at no point do we filter on the source/destination interface or IP.

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
nova-api-metadat-INPUT  all  --  anywhere             anywhere
felix-INPUT  all  --  anywhere             anywhere
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
nova-filter-top  all  --  anywhere             anywhere
nova-api-metadat-FORWARD  all  --  anywhere             anywhere
felix-FORWARD  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             192.168.122.0/24     ctstate RELATED,ESTABLISHED
ACCEPT     all  --  192.168.122.0/24     anywhere
ACCEPT     all  --  anywhere             anywhere
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
nova-filter-top  all  --  anywhere             anywhere
nova-api-metadat-OUTPUT  all  --  anywhere             anywhere
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootpc

Chain felix-FORWARD (1 references)
target     prot opt source               destination
felix-from-3b95a6df-9f  all  --  anywhere             anywhere
felix-to-3b95a6df-9f  all  --  anywhere             anywhere
felix-from-3f082630-ed  all  --  anywhere             anywhere
felix-to-3f082630-ed  all  --  anywhere             anywhere
felix-from-f9787c75-f7  all  --  anywhere             anywhere
felix-to-f9787c75-f7  all  --  anywhere             anywhere

Chain felix-INPUT (1 references)
target     prot opt source               destination
felix-from-3b95a6df-9f  all  --  anywhere             anywhere
felix-from-3f082630-ed  all  --  anywhere             anywhere
felix-from-f9787c75-f7  all  --  anywhere             anywhere

Chain felix-from-3b95a6df-9f (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
RETURN     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
RETURN     udp  --  anywhere             anywhere             udp spt:bootpc dpt:bootps
DROP       udp  --  anywhere             anywhere             udp spt:bootps dpt:bootpc
MARK       all  --  10.0.0.6             anywhere             MAC FA:16:3E:7D:A1:07 MARK set 0x1
DROP       all  --  anywhere             anywhere             mark match ! 0x1
RETURN     tcp  --  anywhere             localhost            tcp dpt:8775
DROP       all  --  anywhere             127.0.0.0/8
RETURN     all  --  anywhere             anywhere             match-set felix-from-port-3b95a6df-9f dst,dst
RETURN     all  --  anywhere             anywhere             match-set felix-from-addr-3b95a6df-9f dst
RETURN     icmp --  anywhere             anywhere             match-set felix-from-icmp-3b95a6df-9f dst
DROP       all  --  anywhere             anywhere

Chain felix-from-3f082630-ed (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
RETURN     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
RETURN     udp  --  anywhere             anywhere             udp spt:bootpc dpt:bootps
DROP       udp  --  anywhere             anywhere             udp spt:bootps dpt:bootpc
MARK       all  --  10.0.0.9             anywhere             MAC FA:16:3E:7E:31:DC MARK set 0x1
DROP       all  --  anywhere             anywhere             mark match ! 0x1
RETURN     tcp  --  anywhere             localhost            tcp dpt:8775
DROP       all  --  anywhere             127.0.0.0/8
RETURN     all  --  anywhere             anywhere             match-set felix-from-port-3f082630-ed dst,dst
RETURN     all  --  anywhere             anywhere             match-set felix-from-addr-3f082630-ed dst
RETURN     icmp --  anywhere             anywhere             match-set felix-from-icmp-3f082630-ed dst
DROP       all  --  anywhere             anywhere

Chain felix-from-f9787c75-f7 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
RETURN     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
RETURN     udp  --  anywhere             anywhere             udp spt:bootpc dpt:bootps
DROP       udp  --  anywhere             anywhere             udp spt:bootps dpt:bootpc
MARK       all  --  10.0.0.8             anywhere             MAC FA:16:3E:2C:11:A3 MARK set 0x1
DROP       all  --  anywhere             anywhere             mark match ! 0x1
RETURN     tcp  --  anywhere             localhost            tcp dpt:8775
DROP       all  --  anywhere             127.0.0.0/8
RETURN     all  --  anywhere             anywhere             match-set felix-from-port-f9787c75-f7 dst,dst
RETURN     all  --  anywhere             anywhere             match-set felix-from-addr-f9787c75-f7 dst
RETURN     icmp --  anywhere             anywhere             match-set felix-from-icmp-f9787c75-f7 dst
DROP       all  --  anywhere             anywhere

Chain felix-to-3b95a6df-9f (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
RETURN     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
RETURN     all  --  anywhere             anywhere             match-set felix-to-port-3b95a6df-9f src,dst
RETURN     all  --  anywhere             anywhere             match-set felix-to-addr-3b95a6df-9f src
RETURN     icmp --  anywhere             anywhere             match-set felix-to-icmp-3b95a6df-9f src
DROP       all  --  anywhere             anywhere

Chain felix-to-3f082630-ed (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
RETURN     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
RETURN     all  --  anywhere             anywhere             match-set felix-to-port-3f082630-ed src,dst
RETURN     all  --  anywhere             anywhere             match-set felix-to-addr-3f082630-ed src
RETURN     icmp --  anywhere             anywhere             match-set felix-to-icmp-3f082630-ed src
DROP       all  --  anywhere             anywhere

Chain felix-to-f9787c75-f7 (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
RETURN     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
RETURN     all  --  anywhere             anywhere             match-set felix-to-port-f9787c75-f7 src,dst
RETURN     all  --  anywhere             anywhere             match-set felix-to-addr-f9787c75-f7 src
RETURN     icmp --  anywhere             anywhere             match-set felix-to-icmp-f9787c75-f7 src
DROP       all  --  anywhere             anywhere

Chain nova-api-metadat-FORWARD (1 references)
target     prot opt source               destination

Chain nova-api-metadat-INPUT (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             calico-vm05.datcon.co.uk  tcp dpt:8775

Chain nova-api-metadat-OUTPUT (1 references)
target     prot opt source               destination

Chain nova-api-metadat-local (1 references)
target     prot opt source               destination

Chain nova-filter-top (2 references)
target     prot opt source               destination
nova-api-metadat-local  all  --  anywhere             anywhere
```

**Comment by lwr20** [comment]
OK - I think I saw this on the CI rig.  After a (failed) CI run, I ran the test_security_groups.py tests manually and saw them fail - this leaves the VMs in that state for manual debugging.  I then logged into Horizon on calico-ci01 to take a look.  

I tailed felix.log on one of the hosts and acl_manager.log and neutron.log on the controller while adding and deleting a rule (ICMP to/from anywhere).  

With help from @matthewdupre we saw that the logs showed the mech_calico plugin working correctly (according to the logs) but ACL manager wasn't seeing the rule updates.  We suspect that the net_subscriber of ACL manager wasn't working in some way, but there were no logs saying so.

**Comment by matthewdupre** [comment]
This issue covers a couple of separate ACL Manager bugs:
- the first is broken support for multiple security groups on one endpoint (fixed in 1bdcf534)
- the second is a silent failure of the network subscriber thread when a security rule for a group with endpoints refers to a group with no endpoints (fixed in e435a12).

**Comment by Lukasa** [comment]
Assuming #156 fixed this issue it should be closed, but I'm nervous enough that I want to leave this open until internal testing confirms the fix.

**Comment by neiljerram** [comment]
@matthewdupre Is there still a plugin problem to investigate here too - in the handling of an endpoint that is in multiple SGs - or did it turn out that the plugin is already OK?

**Comment by matthewdupre** [comment]
My preference would be to close this one down subject to retesting the fixes made, and if the plugin issue is confirmed open a new issue that's actually clear.  This issue already covers multiple bugs, and the diagnostics aren't clear.

**Comment by Lukasa** [comment]
I'm reluctant to lose track of it. If we find that we're still having problems I'm ok with that, but I don't want to lose this issue until it's definitely gone (in all its forms!).

**Comment by matthewdupre** [comment]
Closing this issue down to represent the ACL Manager problems being fixed.  If we can confirm the plugin problem, I'll open a separate issue for that.
